### ISSUE TITLE
[TW-1467] Negation of filters

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1493]
_Profpatsch - on 2014-11-25T02:09:13Z says:_ 

 Sometimes it can be useful to exclude certain tasks from filters.

Example: I want to list (and delete) all tasks that are backups (`pro:system backup`) but exclude task 145 because I need to keep it.

I therefore suggest something like

bq. pro:system backup not 145

which is equal to

bq. pro:system and backup and not 145

with `not` binding strongest.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-11-25T02:09:13Z
Modified: 2014-12-28T03:07:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-11-29T14:53:54Z says:_ 

 Good suggestion, as there is currently no way to override the syntactic sugar for IDs.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-24T04:33:25Z says:_ 

 What am I saying - this should work:

```
$ task pro:system and id != 145 ...
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-28T03:07:26Z says:_ 

 We don't new features, "not 123", when we have support for "id != 123".

**Comment by Xerus2000** [comment]
Please document this operator, couldn't find it anywhere in the Docs!

**Comment by Archie-2021** [comment]
Nice to know about `!=` but it is still different with `not` operator. Since task warrior supports other operators and even supports grouping , it is weird that it is not supporting this one. 

Also it seems like there are a lot missing from documentation and it is not uptodate.

For example as I was searching figured out adding a not to end of a field like `project.not: inbox` will do a similar thing like `!=`. 

How can we help with things we find? Is there a way open a pull request for them?

**Comment by djmitche** [comment]
The docs are in https://github.com/gothenburgBitFactory/tw.org and PRs would be great!

**Comment by smemsh** [comment]
but, importantly, the man pages are in the taskwarrior repo under `doc/man/*.in` and those should arguably contain everything that needs documenting
