### ISSUE TITLE
[TW-1732] ISO 8601 basic date format removed

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1756]
_Michael Eichorn on 2015-12-02T17:19:29Z says:_ 

 In my reading ISO 8601 requires that the basic date format YYYYMMDD be supported alongside the extended format YYYY-MM-DD. Likewise YYYYMMDDThhmm is just as valid as YYYY-MM-DDThh:mm.

The page [http://taskwarrior.org/docs/dates.html] documents the supported date formats and basic format is absent.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-12-02T17:19:29Z
Modified: 2016-01-11T19:49:18Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-12-08T17:43:31Z says:_ 

 Requires?

Taskwarrior supports the unambiguous formats, whereas YYYYMMDD is easily confused for a number or UUID.

**Comment by ghalfacree** [comment]
Request for this to be reconsidered for reopening: I universally use the accepted ISO 8601 YYYYMMDD date format, and would like it if I didn't have to keep putting my tasks in twice because TaskWarrior rejects it unless I go back and add in dashes.

I can't see the format being confused for a UUID, or a raw number, especially when used in things like ```due```.

**Comment by pbeckingham** [comment]
Send me a PR that enables this AND PASSES ALL unit tests, and you're on.  The issues is that 8-digit numbers are ambiguous.
