### ISSUE TITLE
[TW-1817] Allow to choose whether recurring tasks pile up or not, and whether they recur after a duration or on a specific day

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1835]
_modem_down on 2016-06-12T16:49:16Z says:_ 

 Org mode in Emacs has three kinds of repeated tasks, depending on whether you want the tasks to stack up if not completed, and on whether you want them to recur on specific days or after specific durations:

`+`

`.+`

`++`

This is documented here: http://orgmode.org/manual/Repeated-tasks.html#Repeated-tasks

Please can this power over recurring tasks be added to Taskwarrior?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-06-12T16:49:16Z
Modified: 2017-01-16T21:03:08Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-06-12T17:04:51Z says:_ 

 Please check our documentation:
http://taskwarrior.org/docs/design/recurrence.html

**Comment by taskwarrior** [comment]
_modem_down on 2016-06-12T17:18:23Z says:_ 

 I did :)

Taskwarrior is much better than Org mode things like dependency tracking, and sorting tasks based on urgency. But Org mode seems to handle recurring tasks in a more useful way than Taskwarrior, due to having those three distinct kinds of repetition specifier.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2016-06-12T17:56:11Z says:_ 

 The link Paul provided, however, is our design document for the recurrence overhaul effort for 2.6.0 (and not current documentation, which you probably looked into). It would be useful if you could check that your use case is covered.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-16T21:03:08Z says:_ 

 Closing: 7 months, no response.

**Comment by sampablokuper** [comment]
Please can this issue be reopened, and please can you clarify what sort of response you were seeking?

**Comment by sampablokuper** [comment]
@pbeckingham [wrote](https://github.com/GothenburgBitFactory/taskwarrior/issues/1835#issuecomment-365710146):
> Please check our documentation: http://taskwarrior.org/docs/design/recurrence.html

@tbabej [wrote](https://github.com/GothenburgBitFactory/taskwarrior/issues/1835#issuecomment-365710315):
> The link Paul provided, however, is our design document for the recurrence overhaul effort for 2.6.0 (and not current documentation, which you probably looked into). It would be useful if you could check that your use case is covered.

@tbabej, thanks for clarifying that. You were correct: my response was indeed based upon the current documentation, rather than the design document. *Mea culpa*. Allow me to rectify that.

The correspondence between Org-mode's [three kinds of repeated task](http://orgmode.org/manual/Repeated-tasks.html#Repeated-tasks), and the proposals given in http://taskwarrior.org/docs/design/recurrence.html , seems to be:

| Org-mode kind | Proposed TW kind | Instances accumulate if not done/deleted | Next task's due date set to |
|---|---|---|---|
| `+` |  `rtype:periodic` | Y | Latest instance's **due** date + *interval* |
| `.+` | `rtype:chained` | N | Latest instance's **done** date + *interval* |
| `++` | N/A | N | Latest instance's **due** date + *n* x *interval*, where *n* is an integer that is incremented until the next task's due date is in the future |

As you can see, http://taskwarrior.org/docs/design/recurrence.html does not currently propose an equivalent for the third kind of Org-mode recurrence described in the table above.

**Comment by JonasDralle** [comment]
Those are really useful modes of repetition. IIRC repetition is something that requires an overhaul since a long time? There's a [design document](https://taskwarrior.org/docs/design/recurrence) for it which already put effort into it
