### ISSUE TITLE
[TW-1905] GC un-waits tasks, which bypasses on-modify hook processing

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1918]
_Paul Beckingham on 2017-04-02T17:34:27Z says:_ 

 When a task un-waits, it occurs in TDB2::gc, and bypasses hooks.  Instead, the on-modify hook should be called, simply because removing the wait date is a modification.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-04-02T17:34:27Z
Modified: 2017-04-02T17:34:38Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-04-02T17:34:38Z says:_ 

 Thanks to palo

**Comment by tbabej** [comment]
This is going to be fixed (inadvertently) by #2554

**Comment by djmitche** [comment]
Note some comments over on #2554 regarding the fix: whether a task is +WAITING becomes a derived property of the task and the current time, so there is no "change" that happens when it stops waiting, and thus no way to hook into that event.  Think of it more like +TODAY or +MONTH -- there's no way to run a hook at the beginning of the day or month, either.

**Comment by tbabej** [comment]
Agreed here. I guess we could claim this issue will be "fixed" by becoming invalid, as there will be no modification generated when the wait date passes :slightly_smiling_face:
