### ISSUE TITLE
Add a --dry flag

### ISSUE THREAD

**Issue by ad-si** [GothenburgBitFactory/taskwarrior#2022]
It would be cool if there was a `--dry` (or similar) flag to get feedback of what `taks` would be doing, without really storing it into the database.
I imported a lot of tasks and really tried to make sure that it works on the first try, but I still had a few malformed tasks which weren't imported. Would have been better if I could have tried it first in a dry mode.

**Comment by pbeckingham** [comment]
I think what you're asking is equivalent to this:

```bash
$ task import <file>
$ task list
$ rm ~/.task/*.data
```

As such, I don't think it needs a feature, you can import over and over until the data is right.  You can also use the `$TASKDATA` environment variable to import into other locations.

**Comment by ad-si** [comment]
Yeah, thanks for the tip. That's what I came up eventually, too.
Still think a `--dry` flag would be better, but Ok …

**Comment by abaisero** [comment]
I know this is an old issue, but I thought I'd continue the discussion here rather than opening a new one;  since the proposal was seemingly rejected based on the specific circumstances of the OP, I'd like to voice support for adding a --dry mode based on more general usability and learnability concerns.

My motivation is that a --dry mode would provide a simple and effective playground modality to a learning user.  Taskwarrior as a whole is a complex system (I would assume even more complex than what it was in 2018, the original year of this issue), and a novice learning user would benefit a lot from being able to test commands in practice rather than relying exclusively from documentation which is itself somewhat complex.  This is particularly powerful when the effects of a command can be opaque and not immediately clear (e.g., thing of certain things being visible or not based on explicit or implicit filters, which a novice user would be less aware of).  And even in the cases where the effects are clearly visible, it still beats the need to run a command with some level of uncertainty, and then having to undo the change if something unexpected happened.
