### ISSUE TITLE
Taskserver won't validate some durations.

### ISSUE THREAD

**Issue by danipozo** [GothenburgBitFactory/taskwarrior#2045]
Upon adding a recurrent task with `task add My task recur:month+2week`, taskwarrior client will validate the recurrence duration and add the task. However, syncing (`task sync` for the sake of completeness) won't work:

```
Sync failed.  The Taskserver returned error: 500 The recurrence value 'month+2week' is not valid.
```

As far as I know, this is a valid duration. `task calc month+2week` issues `P44D`.

I could solve the issue following the steps [here](https://groups.google.com/forum/#!msg/taskwarrior-dev/JwnnsnprJaI/bwACWSBLBwAJ), however this is only a workaround over what seems to be a bug.

**Comment by matt-snider** [comment]
I'm having the same issue with _2 weeks_:

```
Sync failed.  The Taskserver returned error: 500 The recurrence value '2 weeks' is not valid.
```

I'm using task 2.5.1 and taskd 1.1.0

**Comment by matt-snider** [comment]
Update: After changing _2 weeks_ to _2w_ in the task data dir with sed (i.e. `sed -i -e 's/2 weeks/2w/g' *.data`), I ended up with the same issue but for _3 days_ and then _2 days_ so it seems taskd doesn't like any long-form recurrences.

Any reason why that would be? I'm just following the [durations doc](https://taskwarrior.org/docs/durations.html)

**Comment by mrossinek** [comment]
This is probably a [taskserver](https://github.com/GothenburgBitFactory/taskserver) related issue rather than a taskwarrior one. A quick look into the issues over [there](https://github.com/GothenburgBitFactory/taskserver/issues) suggests it could be related to the issue GothenburgBitFactory/taskserver#104

Reading the discussion over there I am confused as to why that issue is actually closed..

On further digging, I also found GothenburgBitFactory/taskserver#106

**Comment by djmitche** [comment]
Taskserver is deprecated (#3293). The replacement doesn't see the details of tasks so can't get tripped up on things like this.
