### ISSUE TITLE
Collapse project tasks

### ISSUE THREAD

**Issue by nuxeh** [GothenburgBitFactory/taskwarrior#2104]
Hi, is there a way to collapse tasks which belong to a project?

I have large numbers of tasks associated within projects, so that uncategorised tasks are truncated from the bottom of the default `task next` view, and are therefore difficult to review quickly.

I haven't managed to find a way to easily filter out all the tasks assigned to projects from the command line.

**Comment by yellowsquid** [comment]
You can specify `project:` as a filter to select tasks without a project.

**Comment by JonasDralle** [comment]
You could specify a report that suits your need in reviewing these items. [See here](https://taskwarrior.org/docs/report.html)

You can schedule them by setting `scheduled:` or waiting it via `waiting:`.

You could have dependencies (first this, then that, ...) via `dependency:` and hide items which are `BLOCKED`.

Personally I don't plan too far into the future. The further away the point in which I process an item the more likely the current item contents is false. I also don't auto-generate to do items (e. g. from Jira or Mail). These are methods that work for me in order to keep my task database clean and useful. BUt of course you might use TW in a completely different manner than I am.

**Comment by nuxeh** [comment]
Thanks all, very useful. This does offer a number of options to do what i was was hoping, and more. Thanks!
