### ISSUE TITLE
docs page out of date

### ISSUE THREAD

**Issue by slmeyer** [GothenburgBitFactory/taskwarrior#2110]
I am following instructions on page:
https://taskwarrior.org/docs/timewarrior/holidays.html

cd /usr/share/doc/timew/doc/holidays
./refresh
result:
holidata.net does not have data for en-US, for 2019.

reason:
correct format:
   http://holidata.net/ <LOCALE> / <YEAR> . <FORMAT>

Here is an example that requests the 2016 holiday data for the en-US locale:
    http://holidata.net/en-US/2016.json

**Comment by pbeckingham** [comment]
The reason there is no data is that no one i volunteering to help.

**Comment by JonasDralle** [comment]
Closing non-resolved issues which are being ignored due to lacking manpower is not healthy for the project in the long term.
There's a [`help wanted`](https://github.com/GothenburgBitFactory/taskwarrior/labels/help%20wanted) label for issues. This issue seems to be eligible for the [`good first issue`](https://github.com/GothenburgBitFactory/taskwarrior/labels) label.

More attention from outside could be archived by contacting webpages such as up-for-grabs.net <sub>[or any of the here listed pages](https://www.firsttimersonly.com/)</sub> in order to match C++ people who want to contribute but don't know where.

**Comment by pbeckingham** [comment]
Posting issues to the wrong project is not particularly useful.  In this case the issue is stated as "docs page out of date", which is vague and incorrect.  There is a holidata project that has an issue tracker, and ideally, if we want people to help, there should be one issue for every language missing data, as contributors tend to focus on one language.

https://github.com/GothenburgBitFactory/holidata/issues

I'm aware of the labelling options.  The problem is insufficient volunteers to do the things that need to be done.

**Comment by JonasDralle** [comment]
oh okay (y)

**Comment by slmeyer** [comment]
I'm sorry, I was just too quick that day, didn't realize the connections and implications - however, since I made my own holiday file, I can contribute it, should I add it here:
https://github.com/GothenburgBitFactory/holidata/issues
By the way - nice to see a github tracker with just no issues :)
