### ISSUE TITLE
docs page minor error

### ISSUE THREAD

**Issue by slmeyer** [GothenburgBitFactory/taskwarrior#2111]
In page:
https://taskwarrior.org/docs/timewarrior/track.html

I run;
timew track 9am - 11am

Result:
Unrecognized date range: '<date> -'.

This works:
 timew track 9am-11am

**Comment by mrossinek** [comment]
I guess you should be posting this issue at https://github.com/GothenburgBitFactory/timewarrior/issues rather than here..
In any case, I cannot reproduce this issue. You will have to provide some more information on the system and timewarrior version that you are running (i.e. what does timew --version output?)

**Comment by slmeyer** [comment]
OK thanks for replying - I retried it - it was a 'hidden' space between 11 and 'am' that caused the error message.
