### ISSUE TITLE
What is the process for adding to the taskwarrior.org tools/extensions list?

### ISSUE THREAD

**Issue by matt-snider** [GothenburgBitFactory/taskwarrior#2135]
Hi,

I'm curious about the process for adding a tool to the list on the [taskwarrior.org website](https://taskwarrior.org/tools/).

I found [BrunoVernay/taskwarrior-site-test](https://github.com/BrunoVernay/taskwarrior-site-test) but it doesn't seem to be actively maintained.

**Comment by thehunmonkgroup** [comment]
See https://groups.google.com/forum/#!topic/taskwarrior-user/YhJ_9ocCVyg

The broken script has been patched to work, but I don't think it's back in use yet. Also still needs support for GitLab

**Comment by thehunmonkgroup** [comment]
The script in use was https://github.com/BrunoVernay/tw-tools-update, and the fixed branch is at https://github.com/jrabbit/tw-tools-update/tree/2019-refresh

**Comment by matt-snider** [comment]
Thanks for the info. So the current state is that the script works, but there is no automated process for updating the website?

**Comment by thehunmonkgroup** [comment]
That is my current understanding, however, I'm not involved with any of the infrastructure maintenance.

**Comment by pbeckingham** [comment]
The author of the original script and web page is no longer supporting the code. There is a fix, which I need to test. If it works, I will patch. There is no automated solution, typically I would run the script once a week and publish.

Here is what I want, but don't have the time/skills:

1. A Python script that visits both Github and Gitlab, and runs a query looking for Taskwarrior, Taskserver and Timewarrior related projects. The original request was that anyone who references our stuff in the description of the project, is a candidate. All metadata is gathered.
2. Applies a set of known projects that do not show up in the above search, to be included in the results.  This list if initially empty, and is read from an `always_include.json` file.
3. Suppresses a set of projects, by name, so we don't include dead or unrelated projects, by name, read from a `never_include.json` file.
4. Emits the correctly formatted, filtered, combined JSON file that can be committed and pushed. I will automate this.
5. I would like the above to work with no external Python dependencies. I don't want this script to keep breaking as the current one does.

I don't want to modify the existing page or file format unless absolutely necessary.

The above needs to be documented so that it is trivial for someone unfamiliar with the process can get a key, run the script and update the website.

**Comment by thehunmonkgroup** [comment]
@pbeckingham couple things:

1. It's not realistic to have *no* external Python dependencies. For example, the currently working code has dependencies on pygithub and toml -- it would be silly to write custom code for those when good libraries exist to solve the problem.
2. https://github.com/jrabbit/tw-tools-update/tree/2019-refresh meets all the other requirements except these two:
    1. Does not have an 'always include' functionality -- pretty sure this would be trivial to add.
    2. No Gitlab support yet. While I understand the desire to also have this support, hopefully that's not a blocker for deploying the currently working code!
3. Are you sure you don't want to automate the updating of the JSON file? This seems trivial, as the Python script can definitely be run via cron and update a publicly available .json file, which you can point the tools page JS at.

**Comment by matt-snider** [comment]
@pbeckingham @thehunmonkgroup 

Here are my thoughts:

* Regarding the use of dependencies: the script is very straightforward and could, without _extreme_ effort, be implemented without dependencies. But the question is, why? As @thehunmonkgroup has commented, there are existing libraries that already do the things we want to do. I started my implementation this way, and it worked fine until I realized the results were paginated. That in itself is annoying to deal with, and I'm sure down the road there would be other similar annoyances.
* I think the most important thing in keeping this properly maintained is having it in a [GothenburgBitFactory](https://github.com/GothenburgBitFactory)-owned repo. The most fitting place seems to be the [tw.org](https://github.com/GothenburgBitFactory/tw.org) repo.
* The current implementation seems overly complicated: 
    * There is a lot to sift through in the README - just tell me how to use the thing! e.g. I can't see why it would ever be necessary to do automatic classification via machine learning
    * Getting the repository README doesn't seem necessary 
    * Very detailed author information is retrieved, making a request for every single contributor to a project. This seems to me to be overkill. Isn't it enough to get the repository owner? Do we even need to get their display name or can we settle for their login (e.g. "pbeckingham" vs "Paul Beckingham")?
    * I get trying to be organized, but given how little there is to do here, a single file script seems fine
* With the above in mind, I decided to make a simplified and documented implementation at [matt-snider/tw.org](https://github.com/matt-snider/tw.org/). 
    * It doesn't currently search GitLab, but this will be simple to add
    * It looks for all the keywords mentioned instead of just _taskwarrior_ (i.e. _timewarrior_, _taskserver_ additionally)
    * It reads the requested json files (`always_include.json` and `never_include.json`)

Let me know what you guys think.
