### ISSUE TITLE
[TW-167] CalDAV Sync

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#218]
_Jan Losinski on 2011-05-03T22:31:17Z says:_ 

 I think taskwarrior need a CalDAV Sync. This should be easy, easier than implement a own sync implementation like the taskd. The benefit is a broad availability of the tasks managed with taskwarrior such as mobile devices, gui applications (thunderbird, etc) and others.

An example CalDAV implementation using libneon can be found in the syncevolution caldav backend at https://meego.gitorious.org/meego-middleware/syncevolution/trees/master/src/backends/webdav

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-05-03T22:31:17Z
Modified: 2014-04-13T15:51:15Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-04T22:14:32Z says:_ 

 I propose this should be done as an external script, in the fashion of export-xml.{pl,rb,py}.

**Comment by taskwarrior** [comment]
_Jan Losinski on 2011-05-06T21:26:59Z says:_ 

 I mean real two-way-sync, not export and/or import.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-06T21:56:42Z says:_ 

 It definitely overlaps with the task server.  Does it offer any advantages?

**Comment by taskwarrior** [comment]
_Jan Losinski on 2011-05-24T09:38:34Z says:_ 

 Of course: it is a standard! 

So you can use mobile devices or other applications (for example if you have to view/edit your tasks from a plattform not containing a terminal). 

You also can use it with a groupware that provides caldav.

**Comment by taskwarrior** [comment]
_David Patrick on 2011-05-25T14:12:38Z says:_ 

 Jan Losinski wrote:
> Of course: it is a standard! 

Too true, and it opens up a wide array of interoperability. Maybe the best (and probably hardest) thing would be to extend taskd with an option to sync to caldav, so that the feature is complimentary, not competing.
> 
> You also can use it with a groupware that provides caldav.

and/or use it to publish your calendar anywhere.

**Comment by taskwarrior** [comment]
_Eric Fluger on 2011-05-26T22:52:04Z says:_ 

 YES!

Interoperability with CalDAV, or one of the WebDAV derivatives would be very helpful.

(I've recently developed a pressing need for calendar sharing and such, so this have been very much on my mind.)  

There are at least two, probably several interesting ways to conceptualize this.  More options will probably become practical post-refactoring.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-05-30T22:42:55Z says:_ 

 If it happens then after 2.0.0.

Even if caldav is a standard, it is a standard for calendaring, and not handling tasks/todos. Though both might overlap. But taskd and its protocol is light and focuses on taskwarrior. Our primary target. As David wrote, an extension to task/taskd to talk to caldav will be the way to go.

**Comment by taskwarrior** [comment]
_Jan Losinski on 2011-05-30T23:01:48Z says:_ 

 Too bad. Taskwarrior is a nice tool, but its unuseable for me if I cant sync the tasklist with anyone in my office or any of my non-linux devices. Why does anyone think he helps anyone by implementing a isolated application?

And no, caldav is not focused on events. It has also VTODO items. Look at the RFC: http://tools.ietf.org/html/rfc4791

Where is the RFC for the taskd protocol? And where are the implementers?

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-05-30T23:14:10Z says:_ 

 We don't say no. We just defer it. And focus on taskd/taskwarrior integration. 

And yes, we know RFC4791. But we don't think it is the optimal solution for what we want to do!

And yes, you will be able to talk to caldav via some sort of extension. Either written by us or someone else. What do you mean by non-linux devices? Phones? With taskd having an open and documented API there are no obstacles to write a mobile taskd app.

The implementors of taskwarrior are also the implementors of taskd. And the RFC (or better documentation of the API) will be released with taskd. And yes, we had external people looking at it.

**Comment by taskwarrior** [comment]
_Jan Losinski on 2013-03-12T00:13:43Z says:_ 

 Whats with taskd? I see no code! No standarized sync, no real reinvented wheel .. are there any progress for sync and/or interoperability?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-12T02:57:13Z says:_ 

 Jan Losinski wrote:
> Whats with taskd? I see no code! No standarized sync, no real reinvented wheel .. are there any progress for sync and/or interoperability?

Taskd is working well and will be in beta soon.  The code is in a public repository.

**Comment by benyanke** [comment]
I would also love to see interoperability with caldav todo lists. This would vastly open up the landscape.

Any chance it could be reconsidered?

**Comment by binaryplease** [comment]
As much as I like taskwarrior it's just not usable for me if I can't sync it with other devices like my phone or even thunderbird. I don't know if the RFC or the protocol is "optimal", as a user I don't understand why you woudn't want to implement sync via a de-facto standard. Please reconsider this, it would make the application a lot more practical for quite a few people.

**Comment by ngortheone** [comment]
I wildly support the motion.
But first  a small clarification to statements above. CalDAV is a transport protocol that describes how to exchange iCalendar data between network devices.

What we should start with is changing Taskwarriors data model from home-grown json (in some places it is not even a json - look at your `pending.data` - wtf is that???) to a [iCalendar - RFC 5545](https://tools.ietf.org/html/rfc5545). Only after that we can talk about CalDAV.

iCalendar is a very flexible data format that can be extended with custom fields (to host any UDA's for example) and it is understood by countless amount of tools and apps. iCalendar data can also be serialized to json - [RFC7265](https://tools.ietf.org/html/rfc7265).

Yes this is a lot of work, but guys, let's be real - taskwarrior is stagnant and it lacks adoption. It needs wider audience, but who wants to limit him/herself to a desktop only client?

This is my personal reason why I stopped using Taskwarrior (among others) - no mobile experience, no library to write clients with (taskwarrior binary is NOT USABLE as a library without full code rewrite - i tried, it dumps all to stdout, your only real option is to parse stdout...). I had custom import/export scripts to sync with my zimbra server, I used that hacky android app. After a certain moment you realize that this simply does not scale. Imagine how you are going to convince a non-tech person to generate and install SSL certs to his/her phone, I know MTLS is cool, but look around - nobody does that because this is not user friendly.

Sorry, for divergence. I spent a lot of time trying to work around taskwarriors limitations and issues and I gave it a lot of thinking. Data model is one of the fundamental things that has to changes. That and then separate client binary into library and fronted to it to allow writing non-desktop apps. Both things are capital investments that can't be done overnight...

**Comment by binaryplease** [comment]
Since there seem to be enough people interested, I guess what we need here is a decision from the maintainers. I (and I hope others) may be able to help out and split the required work and submit PRs if @taskwarrior is even interested in going in this direction and there is hope to get something like this merged.
