### ISSUE TITLE
TimeWarrior track include named day and time

### ISSUE THREAD

**Issue by jessebett** [GothenburgBitFactory/taskwarrior#2185]
I am trying to record a closed interval from yesterday, however timewarrior does not seem to allow any of the following syntax, and the docs don't show an example. The following examples are from the [Track page in the timewarrior documentation](https://taskwarrior.org/docs/timewarrior/track.html)
```
$ timew track :yesterday 'Training Course'
$ timew track 9am - 11am 'Staff Meeting'
```

However, I would like to record a closed interval that was both yesterday and at a specific interval. None of the following work:
```
timew track yesterday 9am - 11am "thing" 
# Unrecognized date range: '<date> <date> - <date>'.

timew track :yesterday 9am - 11am "thing" 
# Unrecognized date range: '<date> <date> - <date>'.

timew track yesterdayT7:30 - yesterdayT8:30 "thing"
Unrecognized date range: '-'.
```

Is there really no way to override the default 0:00:00 time for named days like `yesterday`?

**Comment by mrossinek** [comment]
It would be better to move this issue to the [timewarrior](https://github.com/GothenburgBitFactory/timewarrior) repo, but I'll answer your question anyways. But please consider closing this issue afterwards.

As you can see [here](https://taskwarrior.org/docs/timewarrior/dates.html), `yesterday` gets expanded to the date at midnight. Thus, this placeholder already includes a time of day and cannot be combined with a different time (at least currently).

See the following issues for further discussion:
https://github.com/GothenburgBitFactory/timewarrior/issues/130
https://github.com/GothenburgBitFactory/timewarrior/issues/196

In order to achieve what you would like to do I would do something of the following options:
* Replace `yesterday` with the actual date, specified in one for the standard formats.
* Track the interval as a dummy with the correct length starting at midnight and then [move](https://taskwarrior.org/docs/timewarrior/corrections.html) it.
* Or you could check out one of [these other syntaxes](https://taskwarrior.org/docs/timewarrior/interval.html) for specifying intervals which does not help with the problem but might be more intuitive. E.g. `timew track 2019-07-02T09:00 for 2h "thing"` or `timew track 2h after 2019-07-02T09:00 "thing"`

**Comment by jessebett** [comment]
@mrossinek Sorry about that, I did not realize there was a distinct timewarrior repo because I got here by clicking the issue tracker under Support, and timewarrior lives inside taskwarrior website. Thanks for your answer, I opted for now to write the actual date in the standard format. Will weigh in on the discussion threads you linked. Thanks!
