### ISSUE TITLE
[feature request] Make ~/.config/task the default data directory

### ISSUE THREAD

**Issue by gitjeff2** [GothenburgBitFactory/taskwarrior#2203]
It would be nice to have the data directory location in `.taskrc` default to `data.location=~/.config/task`. It's current accepted best practice on many Linux distros to prefer the `~/.config` directory for user specific configuration files whenever possible.

I realize the current default can be easily overridden at install time or changed later by the user. It just makes the installation a bit smoother reduces dot directory clutter inside of home directories.

**Comment by pbeckingham** [comment]
I have no interest supporting the useless XDG "spec".  This is already supported via overrides as you say, there is no need for this.

**Comment by eddsalkield** [comment]
The XDG Base Directory specification is hardly useless; it promotes good standards for storing user configuration files in a unified directory, rather than scattered throughout $HOME.  Adopting the standard in taskwarrior would be an example of best practice, as the configuration files would be located where users expect.  Expecting users to junk up their environment, add aliases, or create an additional wrapper shell script just to get taskwarrior to conform to the most widely adopted configuration standard seems nonsensical.  In case you want evidence of the wide adoption of the XDG spec, see neovim, htop, sway, systemd, vlc, pulseaudio, podman, etc.

Would you consider reopening this issue, since the patch is trivial yet so helpful?

**Comment by zingyb** [comment]
@pbeckingham , you may have no interest, but it's apparent that others do have interest.

If this were Windows would you be annoyed if someone asked for %appdata% support, or ~/Library for macOS?

XDG is the equivalent here, and by expressing hostility to it implies that Linux+some other OSes are not valuable.

The XDG spec has been here for some years and is not going away. Please don't make it a worse experience because you disagree with it.

**Comment by ainola** [comment]
Yes, another request to re-open this.

**Comment by Neurognostic** [comment]
Would really like to see taskwarrior respect XDG variables like most other modern programs.

**Comment by tbabej** [comment]
Support for taskrc location defined by `XDG_CONFIG_HOME` implemented in #2316. The other data locations can be then defined in the taskrc file itself.
