### ISSUE TITLE
[Feature request] Dependency Chains

### ISSUE THREAD

**Issue by Andonome** [GothenburgBitFactory/taskwarrior#2225]
# Workflow
I often find myself with projects that clearly require one thing to be done before another:

> task add project:A.first_plan part one ; task add project:A.first_plan part two dep:1; task add project:A.first_plan part three dep:2

## Problem

This takes ages to set up dependencies, and dependencies have to be set for many projects.

## Suggestion

Add some command to string tasks, either so that the task depends upon the previously made task, whatever it was.

**Comment by JonasDralle** [comment]
IMO the `depends` field works fine.
I usually sketch out projects maximum 2 dependencies deep. Rarely a chain of 3 dependencies.

This is because usually you will know best what next to do after having finished the steps before. Maybe there are more intermediate steps than previously anticipated and/or goal changed and/or ...

I do _Getting Things Done_ and usually I write down the grant vision on a piece of paper, sketch the path towards that goal and then just put the next few items into TaskWarrior. When I don't know what next to do I can get back to the paper and be remembered about that rough steps were considered.

(this of course has nothing to do with implementing this ticket but instead of asking "is it healthy to use such a tool?")

**Comment by Andonome** [comment]
I found there's a tag for it, called LATEST, so the process can be made with an alias.

> alias tal='task add dep:"$(task +LATEST uuids)"'
