### ISSUE TITLE
README.md doesn't mention libuuid (refer to INSTALL?)

### ISSUE THREAD

**Issue by tbm** [GothenburgBitFactory/taskwarrior#2291]
README.md says you need:

  * git
  * cmake
  * make
  * C++ compiler, currently gcc 5.0+ or clang 3.4+ for full C++14 support

But actually you also need libuuid, as mentioned in INSTALL.

Since INSTALL has install info, does it make sense to duplicate that info (without some important details like libuuid) in README.md?  Maybe README.me should just refer to INSTALL.

**Comment by mrossinek** [comment]
I agree that it probably makes sense to refer the reader to `INSTALL` for the instructions on how to compile Taskwarrior from source. Since this is also a very straight forward cmake-type installation, I don't think the README degrades by having the installation section essentially almost completely removed.

Before doing so, however, we may want to merge the information on how to install from a git clone to INSTALL compared to the currently (only) method based on a tar ball.

**Comment by djmitche** [comment]
Readme no longer includes installation info.
