### ISSUE TITLE
Undo command does not support bulk edits well

### ISSUE THREAD

**Issue by bbappserver** [GothenburgBitFactory/taskwarrior#2301]
Sometimes I need to make a bulk change and I screw it up.  It would be nice if taskwarrior could make a savepoint before I do this.  Right now I have to tediously go through an undo everything, since undos don't seem to be coalesced.
- `task savepoint [name]` create a savepoint (optional with name)
- `task savepoint [name] pop [--keep]` rollback to the previous or named savepoint (deletes), keeping if specified
- `task savepoint <name> delete` delete the named savepoint

This is essentially a convenience method that creates an bunch of numbered+named exports in the taskwarrior files. And does an import with replace.

**Comment by tbabej** [comment]
We are generally wary about adding new commands at this point (in order to keep UI reasonably simple). That said, I think this could be reformulated as `task undo` being too granular, and in some cases undo-ing multiple changes at once could be reasonable.

Maybe something like `task undo <timestamp>` which would undo everything until a given time, i.e. `task undo now-1h` would achieve the same effect? (note this functionality does not exist)

**Comment by tbabej** [comment]
Another idea that I just had would be to simply keep track of which modifications were caused by the same invocation of the task command, perhaps via randomly generated "modification UUID". This information could be purely kept in the `undo.data`, and would allow us easily roll back the entire bulk edit.

**Comment by Joe-Withey** [comment]
Hi, I was looking for an issue around this topic as i just had to do a mass undo. I would find the addition of a `-y` flag useful as I am able to see in the undo.data file how many undos I need to do to get back to a point which means I just need to script that command to happen n times, but having to confirm the undo is a pain.

Another idea could be to allow the use of an undo.data file as an argument, so copy or cat the portion of the file for the undo command to read, the same approach could potentially used for redo as well if at all possible?

**Comment by djmitche** [comment]
`task undo` now "reverses" operations performed on the DB, up to the latest undo point. I think a bulk operation would create one undo point, so this may now work as expected.
