### ISSUE TITLE
Feature: Alias verbs and predicates in .taskrc

### ISSUE THREAD

**Issue by bbappserver** [GothenburgBitFactory/taskwarrior#2302]
It would be nice if we could specify aliases to verbs such as `modify` and predicates such as `project:` to save on typing
Example verb aliases
- `add` = `a`
- `modify` = `m`
Example predicate aliases
- `project:`=`p:`
- `recur:`=`r:`

Example usage
```sh
task "id>5 id<10" m p:taskwarrior #Assign projects 6 through 9 to project taskwarrior
```

**Comment by insanerwayner** [comment]
For the two verbs this can be accomplished already:
```
alias.a=add
alias.m=modify
```

The project and recur aliases don't seem to work, however.

**Comment by tbabej** [comment]
"Predicate" aliases (which really are attribute names) can already be shortened to their unique prefixes, i.e. `task pro:Home`. As it seems that the need here is to use shortened versions of the attribute names, that should be already achievable via that mechanism.

Your example in the issue is doable as `task 6-9 mod pro:taskwarrior`, which I'm sure is sufficiently short. I'd recommend perusing [the documentation](https://taskwarrior.org/docs/), which contains more tips and tricks how to use Taskwarrior.
