### ISSUE TITLE
[feature request] caldav sync

### ISSUE THREAD

**Issue by eoli3n** [GothenburgBitFactory/taskwarrior#2418]
Is that possible to sync with CalDav ?

https://github.com/tasks/tasks/issues/1256

**Comment by tbabej** [comment]
Not natively. There is https://github.com/erikh/calwarrior that provides this functionality outside of core.

Note that taskwarrior is not related to the tasks project.

**Comment by eoli3n** [comment]
Yep, just linked it, you can see that people are searching for a desktop client which supports caldav.
Thanks for calwarrior.

**Comment by aquelehugo** [comment]
A big +1 here.

This is an ancient request. It goes back to 2011, before the project migration to github: https://github.com/GothenburgBitFactory/taskwarrior/issues/218

I loved the taskwarrior concept but most third-party frontends suck, specially the Android ones. Having an official syncing solution to a widely used standard would be really awesome.
`calwarrior` seems like a partial solution, but it is a small side project that has known bugs like not updating due dates. On top of that, last commit was more than six months ago.
Another third-party syncing solution is [caldavwarrior](https://gitlab.com/BlackEdder/caldavwarrior), which doesn't support dependent tasks and is also abandoned.

We really need an official solution to allow for a trustworthy and flexible usage.

**Comment by hacktivista** [comment]
+1 it would be a great feature... Do we know if maintainers would be willing to merge such contribution?

**Comment by insanerwayner** [comment]
My solutions for this is a **pre-load** hook in calcurse. There may be a better way to to do this with **taskwarrior** hooks but this has worked fine for a few years:

```
#!/bin/bash
task -WAITING and -PARENT and \(+OVERDUE or +DUETODAY or sched.before:today or sched:today \) _ids | {
    while read -r i
    do
        echo "[0] $(task _get "$i.description" 2> /dev/null)"
    done } | sort --unique > "$XDG_DATA_HOME"/calcurse/todo
```

**Comment by lasdfdv** [comment]
Getting taskwarrior tasks work with caldav is the dream. A (my) usecase: 
- Main taskmanagement (business and private): TW
- TW -> Caldav -> Nextcloud instance 
- then to MS Outlook via the beautiful caldavsynchronizer (MS due to workplace...)

**Comment by jspricke** [comment]
Just to add my implementation to the list:
https://github.com/jspricke/radicale-remind
with
https://github.com/jspricke/python-icstask

**Comment by notflip** [comment]
Is there any news on making caldav sync work?

**Comment by bergercookie** [comment]
This is now supported in https://github.com/bergercookie/syncall and  its `tw_caldav_sync` executable.

**Comment by borisrunakov** [comment]
> This is now supported in https://github.com/bergercookie/syncall and its `tw_caldav_sync` executable.

Great  work ! Much appreciated!

**Comment by mrusme** [comment]
`syncall` unfortunately doesn't seem to be super actively developed and seems like a bandaid solution. Would a native implementation of CalDAV into taskwarrior be something the core devs would be interested in? At least for me personally it would spare me of running an additional service (`taskd`), that is another potential security risk on my CalDAV machine. 

Is there any added benefit that `taskd` has over CalDAV? From what I see taskwarrior could benefit immensly by using CalDAV as backend, as there are plenty of mobile and desktop apps available that use CalDAV already, allowing taskwarrior to integrate nicely into an existing ecosystem.

**Comment by bergercookie** [comment]
> syncall unfortunately doesn't seem to be super actively developed

Apologies on this, development has indeed been slow for the past few months but that been said, it's still actively developed :)

One update since my last post is that now `syncall` supports syncing `taskwarrior` tasks with the tasks of a `caldav` server. It's not 100% bulletproof yet but I'm using it automatically on a daily basis and IMHO it's worth giving it a try

**Comment by djmitche** [comment]
Hi! So, Taskwarrior's built-in sync is meant to precisely replicate tasks between Taskwarrior instances. I believe we briefly looked at caldav along with a few other options as a backend for doing so, when designing taskchampion, and determined that none of the options were sufficient.

That said, the new architecture will make it easier to build integrations that bridge things between Taskwarrior and other systems such as caldav. I'm not sure exactly what funcitonality you're looking for, but as an example I sync from various bug-tracking systems like GitHub issues into Taskwarrior.

With the Taskchampion "core library", it would be pretty easy to build some automation to either bridge events in some CalDAV store into Taskwarrior, or bridge tasks from Taskwarrior into some CalDAV system. It sort of sounds like that's what syncall is doing? The intended way to do this in the future is to embed Taskchampion in the automation, with its own replica of your task database, and then sync that replica with the replica you access with the `task` command.

**Comment by tigger04** [comment]
Just wanted to add my voice of support for this request

CalDAV sync is the sole reason I stopped using TaskWarrior - inability to sync with my phone is a deal breaker for me unf. Every now and then I toy with TW and lament at how slick it is, but the 3rd party libraries seem to come and go and involve an unrealistic amount of configuration and on a whim and a prayer for your data's integrity, I remain using a more solid set of tools.

**Comment by djmitche** [comment]
As described in my previous comment, Taskwarrior has a dedicated sync model of its own for connecting Taskwarrior replicas (via TaskChampion), and that has a very different model from CalDAV. So the term "sync" might be overloaded here - this would be an "integration" with a CalDAV server. So, this would not be a feature of Taskwarrior, but done via integrations like syncall. It's great to see such enthusiasm for this feature. Perhaps some of that can be directed toward supporting ongoing syncall development?

I agree that the ecosystem of integrations with TW has been generally broad and shallow. People build tools to suit their needs, and once those needs are satisfied, development slows down, perhaps with major functionality missing where the author doesn't need it. In some sense, that's the nature of open-source software. But maybe we could do better. If anyone has ideas, those would be good topics for GitHub discussions, the discord channel, or even the periodic video meetings.

I'm going to close this issue since there's no action for Taskwarrior here, but feel free to link from here to places such as syncall where this interest and energy continue.

**Comment by tigger04** [comment]
I really hate to sound ungrateful to developers who give their time freely to develop awesome tools and software for us.

In reading the response when I see 'if anyone has ideas,' 'good topics for discussion', 'periodic video meetings' etc, I find myself open to the idea of putting my money where my mouth is and seeing if I could contribute to the code or in some other way to making an integration work.

But then when I reached ..

> I'm going to close this issue since there's no action for Taskwarrior here, but feel free to link from here to places such as syncall where this interest and energy continue.

I very much get the vibe that there really is no appetite for getting TW to support an open standard such as caldav natively as a first class citizen.
Am I wrong? The issue is closed, so I'll move on as well.

**Comment by mrusme** [comment]
@tigger04 I am suggesting to move away from Taskwarrior as a whole and instead build on top of tools for which DAV is a first class citizen. While I don't want to rain on anyone's parade, I feel like Taskwarrior has failed to listen to its community and evolve into something that is truly useful for people. Instead, it appears it has decided to stick to its own *"walled garden"* with the use of a client/server protocol that nobody else speaks and that is a PITA to integrate. I initially tried to build a [taskd-to-dav proxy in caldr](https://github.com/mrusme/caldr/tree/taskd) but I gave it up after seeing how tedious it is to work with the protocol and *translate* it into dav.

**Comment by tigger04** [comment]
@mrusme I see you referenced this topic from [todoman](https://github.com/pimutils/todoman/issues/411) which is actually one of the tools I landed on for my daily workflow, so I will link back here for anyone finding this topic and looking for CLI tools on an open standards footing:

- [todoman](main/jfdi/478c1b13cb13456ba18389cbc8d6e271@nospoon.ics) (CLI todo/task manager - simple but effective, natively stores data in .ics aka iCalenddar format
- [khal](https://github.com/pimutils/khal) (CLI/TUI calendar app, natively stores data in .ics aka iCalendar format)
- [vdirsyncer](https://github.com/pimutils/vdirsyncer) - 2-way sync between .ics and calDAV, above two apps support vdirsyncer as a first class sync agent

cheers
