### ISSUE TITLE
Follow-up tasks

### ISSUE THREAD

**Issue by MMesch** [GothenburgBitFactory/taskwarrior#2460]
#### To request a feature...

I frequently find myself in the situation of marking a task as `done` and immediately adding another with the same project and tags. This is somewhat clunky right now because all the meta info stored in the task that was just finished has to be typed again although a follow up task very often has the same project and tags.

I wonder if something like `task follow 5` that adds a new task automatically copying its meta information wouldn't be able to simplify this a lot. This would be especially helpful because it lowers the barrier to adding smaller tasks. I am sure that there are other ways to design this.

**Comment by kwoot** [comment]
Nice idea! And "task follows 5" would make new task with depends on 5 set.

**Comment by MMesch** [comment]
> And "task follows 5" would make new task with depends on 5 set. 

That's a good idea I think. I am just wondering how the workflow would look like. Would `follow` automatically mark the last task as `done`? Because if you type `task 5 done` before, you can't type `task follows 5` afterwards anymore because it loses it's ID.

**Comment by tbabej** [comment]
This is quite specific and while I don't think it will make it to the core in this form, I believe it will be addressed by the planned "rule engine" feature that will allow you to specify custom commands.

In the meantime, the beauty of TW is that this can be should be addressable by a simple shell script, for example by combining `task duplicate` and `task mod`. Alternatively, you can use DOM references to copy the values from one task to the other, i.e.: `task 3 mod project:5.project` will copy project from task ID 5 to task ID 3.

Also, look into the context feature - in 2.6.0 this will also apply on `task add`, which would to a large extent address what this issue is asking for.

**Comment by MMesch** [comment]
@tbabej . It makes sense to have this addressed via custom "rule" commands although followup tasks are quite common in many task management systems so having a default doesn't sound outrageous either.

Regarding shell scripts that combines commands, I started using taskwarrior shell more and more. Can you script there or even use bash operators like `&&`?

**Comment by tbabej** [comment]
> Regarding shell scripts that combines commands, I started using taskwarrior shell more and more. Can you script there or even use bash operators like &&?

I don't think so, I was referring to plain old bash scripts. You can integrate them through a combination of `alias` and `execute`, i.e. something like: `alias.follow=execute tw-follow`, where `tw-follow` is a bash script implementing your custom behaviour.

**Comment by MMesch** [comment]
Thanks that works for me!

**Comment by MMesch** [comment]
Just for the record. I added this to my bashrc:

```
      function tf() {
          task duplicate $1
          uuid=$(task +LATEST uuids)
          task $uuid mod ''${@:2}
      }

```

I didn't manage to use `alias.follow` with arguments. Is this possible to pipe arguments through taskwarriors `execute` command?

**Comment by JavaZauber** [comment]
I too find myself quite often to use `dup` only to change dependency and name. Usually after sending some e-mail I create a `+waitfor` task for it
