### ISSUE TITLE
Named date eod should be last minute of today and not first of tomorrow

### ISSUE THREAD

**Issue by vizcay** [GothenburgBitFactory/taskwarrior#2519]
```
$ task --version
2.5.3
$ task add XXX due:eod
$ task +TODAY list
No matches
```

Is completely unlogical for me.. if a task dues by the end of today, how is not due TODAY but TOMORROW?

Proposal: make eod set time to 23:59 that is what I manually end up doing.

**Comment by tbabej** [comment]
Hi @vizcay, thanks for the bug report. This is actually behaving [according to the documentation](https://taskwarrior.org/docs/named_dates.html).

That said, I can see how this is not playing nice with other parts of TW, such as the `+TODAY` virtual tag or fuzzy matching for tasks that are due today in general.

Since Taskwarrior operates with second precision, I'd suggest modifying the proposal for `eod` and others be _last second_ of the given day, that is `23:59:59`.

**Comment by tbabej** [comment]
For what it's worth, I actually always felt that the default time component of `00:00:00` for all named dates is a bit rigid. There is a hook that I authored that allows you to specify default hour in the day:

https://github.com/tbabej/task.default-date-time

This would allow you to configure your default "time" for the named dates to be, for example, 16h offset. Therefore doing `task add I have to do this today due:today` would have due date today at 4pm.

**Comment by vizcay** [comment]
> Hi @vizcay, thanks for the bug report. This is actually behaving [according to the documentation](https://taskwarrior.org/docs/named_dates.html).

Hi @tbabej and thanks for your reply but documentation is conflicting then here, please check https://taskwarrior.org/docs/dates.html where it states:

> eod | Current local date, with time 23:59:59.

**Comment by tbabej** [comment]
Thanks for the pointer. Looks like we should treat this as a regression then. Documentation will also need to be unified on this topic.

**Comment by tbabej** [comment]
Indeed, this is a regression, as 2.5.1 behaves as if `eod` is the last second of the day:

```
[warrior@tw-v2.5.1 ~]$ task calc eod
2021-07-03T23:59:59
```

**Comment by smemsh** [comment]
Was wondering this myself, as it's the behavior in the latest release version 2.5.3, but differs from 2.5.1.  However there must be some reason this was changed originally.  Does anyone know why? It seems it was done explicitly this way in 2017, including comments in `libshared/src/Datetime.cpp` above `Datetime::parse_named()` where the varios `eo*` are clearly following the next-interval 00:00:00 pattern (these comments were not changed in your commit btw @tbabej, fyi).  It doesn't look like it was considered a "regression" at the time but rather an enhancement.  A test was explicitly changed to accommodate it in ce7f2e7 and previous behavior was referred to as the "old" way.

A couple other things to consider:
- with the new change, the date filter `before:eoy` would fail to match a task from the last second of the year
- is there any implication with timewarrior? it seems to also expect the 2.5.3 behavior, as documented in https://timewarrior.net/docs/dates/ and there's even included another alias `eocm`, `eocy`, etc to get 2.5.1 behavior.

I was also surprised by the counter-intuitive behavior of `eod` to be the first minute of the next day, and the recent change "feels" correct, but it might not be so simple.  If thought of as a "boundary" rather than a time interval with a dimension, the start of the next day is actually identical to the end of the current day, so it may be more correct (otherwise, it leaves a gap of one second in the current day which matches neither `before:eod` or `after:eod`).

**Comment by tbabej** [comment]
Yes, I agree with you @smemsh that this was a deliberate choice in the past. Unfortunately the reasoning was not documented, so I could not evaluate its merits.

We could keep the 2.5.3 behaviour and try to address the issue that Pablo has raised here, for example, by being smart about evaluating `due:today` filter and allowing `today` to also match the first second of `tomorrow`, but you'd still see tomorrow's date if you were using a dateformat that only has a date resolution (i.e. "%Y-%m-%d").

> is there any implication with timewarrior? it seems to also expect the 2.5.3 behavior, as documented in https://timewarrior.net/docs/dates/ and there's even included another alias eocm, eocy, etc to get 2.5.1 behavior.

The 2.5.3 behavior is actually not documented there, the line defining the `sod` and `eod` says:

```
sod, eod                              Current date at 0:00:00 and 23:59:59
```

This corresponds to the current 2.6.0 behaviour.

> with the new change, the date filter before:eoy would fail to match a task from the last second of the year

You make a good point here. But that's actually consistent across the releases, and is the consequence of the `before` attribute modifier being mapped to the `<` operator (and not the `<=`). In other words, this is not something that has changed between 2.5.3 and 2.6.0:

```
[warrior@tw-v2.5.3 ~]$ task add test due:eoy
Created task 1.
[warrior@tw-v2.5.3 ~]$ task due.before:eoy
[task next ( due.before:eoy )]
No matches.
```

**Comment by smemsh** [comment]
> Yes, I agree with you @smemsh that this was a deliberate choice in the past. Unfortunately the reasoning was not documented, so I could not evaluate its merits.

Possibly the committer @pbeckingham can comment as to the rationale?

> We could keep the 2.5.3 behaviour and try to [... be] smart about evaluating due:today but you'd still see tomorrow's date if you were using a dateformat that only has a date resolution (i.e. "%Y-%m-%d").

Hmm, yes, that would be odd to see the due date as tomorrow if it was really today.  Then again, tomorrow is when today is over.  We really have all day today to finish such a task.  The first minute of tomorrow, it would be overdue, but not before.  This is a typical ambiguity with a due date: does the time allowed to work on something end with a circle-closed interval endpoint or circle-open? I did a quick web search and it does seem that the common understanding of a due date is circle-closed, which would support using the 2.5.1 way.

> [timewarrior actually documents the 2.5.1 / new 2.6.0 way]

Yes, you're right, I was looking at `eom` and got confused by the language.

> > with the new change, the date filter before:eoy would fail to match a task from the last second of the year

> You make a good point here. But that's actually consistent across the releases

Because it's consistent doesn't make it right.  It seems like a bug that a task one happened to complete in the last second of a given year would not show up in a filter for `end.before:eoy` for example.  However I can't think of a way to solve this corner case, and your solution is probably the most intuitive.  I suppose there will have to be an orphan invisible second at each boundary...

Since this change won't be in a taskwarrior release until 2.6.0 (which could be in development for some time), do you think it's ok to run 2.5.3 pegged to a recent libshared to get the new behavior?

**Comment by tbabej** [comment]
> However I can't think of a way to solve this corner case, and your solution is probably the most intuitive.

Well, there is a solution, but it would introduce another semantic change and we need to weight whether it's worth the potential cost for users. In particular, this is how `after` and `before` attribute modifiers are defined:

```
  before, below     due.before:today   due < today          Exact date comparison
  after, above      due.after:today    due >= tomorrow      Exact date comparison
```

there is nothing preventing us from defining `before` as `<=` operator instead of `<`. Using `<=` already does what you want:

```
tastask [warrior@tw-2.6.0 ~]$ task add test due:eoy
Created task 1.
[warrior@tw-2.6.0 ~]$ task due.before:eoy
[task next ( due.before:eoy )]
Filter: ( status = pending and limit:page ) and ( due < eoy )
No matches.
[warrior@tw-2.6.0 ~]$ task 'due <= eoy'
[task next ( due <= eoy )]

ID Age   Due  Description Urg 
 1 21s   5mo  test         2.4

1 task
Filter: ( status = pending and limit:page ) and ( due <= eoy )
```

> Since this change won't be in a taskwarrior release until 2.6.0 (which could be in development for some time), do you think it's ok to run 2.5.3 pegged to a recent libshared to get the new behavior?

I'd recommend not doing that. A better choice would be to simply build 2.6.0 and use that. It should be relatively stable, and actually has more bugs fixed than 2.5.3 :slightly_smiling_face: we're hoping to do a release relatively soon (single-digit weeks).

**Comment by smemsh** [comment]
> there is nothing preventing us from defining before as `<=` operator instead of `<`

Yeah, I saw that in your first comment, but it seems funny: "before" means "before," not "up to and including."  This is really just moving a similar "semantic change" to a different location, I don't think it's any better a solution than keeping `eo*` as first second of next interval.  But it might not be worse either.  I'm not sure...

One idea is to add a "by" so that `due.by:eoy` uses `<=` and `due.before:eoy` uses `<`, but not sure it's worth adding another named date, especially because the difference would have to be explained in documentation.  Also, it modifies things besides `due` ie `start` or `end` or etc and `by` doesn't read right outside the context of `due`.  Maybe not a good idea.

Perhaps the best course of action is to do nothing (leave it as you changed it) until there's other bugs filed (or comments added here).  The corner case may never come up in practice.

**Comment by tbabej** [comment]
> One idea is to add a "by" so that due.by:eoy uses <= and due.before:eoy uses <

I have to say I actually quite like that :thinking: personally I am a fan of using attribute modifiers over having to type expressions such as `due <= eoy`, because those have to be escaped or quoted on the CLI and are a bit more cumbersome to type.

**Comment by smemsh** [comment]
naive implementation seems to work:
``` cpp
--- a/src/CLI2.cpp
+++ b/src/CLI2.cpp
@@ -1341,6 +1341,11 @@ void CLI2::desugarFilterAttributes ()
           op.attribute ("raw", ">");
           rhs.attribute ("raw", value);
         }
+        else if (mod == "by")
+        {
+          op.attribute ("raw", "<=");
+          rhs.attribute ("raw", value);
+        }
         else if (mod == "none")
         {
           op.attribute ("raw", "==");
```
```
 $ src/task calc eoy
2021-12-31T23:59:59

 $ src/task add eoytest due:eoy
Created task 1.

 $ src/task due.before:eoy
No matches.

 $ src/task due.by:eoy

ID  AGE    DUE   DESC     URG 
1  27s    5mo   eoytest   2.4
```

**Comment by tbabej** [comment]
Nice, I think you should also add it into the following array:

```c++
// Supported modifiers, synonyms on the same line.
static const char* modifierNames[] =
{
  "before",     "under",    "below",
  "after",      "over",     "above",
  "none",
  "any",
  "is",         "equals",
  "isnt",       "not",
  "has",        "contains",
  "hasnt",
  "startswith", "left",
  "endswith",   "right",
  "word",
  "noword"
};
```

Now we only need docs, tests and release notes :slightly_smiling_face:

**Comment by smemsh** [comment]
I'll give it a try.  The ChangeLog will want a separate issue for it, so I've made #2536
