### ISSUE TITLE
Enhancement: Add a time componenet to named dates ex. friday@1630

### ISSUE THREAD

**Issue by dyslexicdesigner** [GothenburgBitFactory/taskwarrior#2548]
Named dates are wonderful and convenient but they always default to 00:00:00 Local time.
It would be grand to add a time component to it. Using the symbol @ is convenient to parse and flows syntactically especially for any one with military training.

Examples ...
Friday at 16 hundred -> friday@1600
3rd at 9 AM -> 3rd@0900

I regularly have tasks that need to be completed in time for a meeting later in the week. But having to figure out the date of Thursday when it's Monday, I have to figure todays the 30th. So Thursday is what the 1st, no maybe it's the 2nd? how many days are in august? but it needs to be done by 10 AM if I want to specify the time specifically I need to figure out the date instead of just the day. It's a pain.

**Comment by tbabej** [comment]
Hi @dyslexicdesigner, thanks for the suggestion! You can actually already do that using the following syntax:

`task add finish the paper by noon tomorrow due:tomorrow+12h`

Perhaps we need to make sure this is documented at more visible places, because this question already came up once or twice :slightly_smiling_face: 

Also, you can test various expressions with `task calc`:
```
[warrior@tw-2.6.0 ~]$ task calc friday+16h
2021-07-30T16:00:00
[warrior@tw-2.6.0 ~]$ task calc 3rd+9h
2021-08-03T09:00:00
```

**Comment by dyslexicdesigner** [comment]
Thanks for the information. I did not notice that functionality in the documentation but it may be somewhere I did not look.
Good to know about the 'task calc' as well. 
Thanks

**Comment by tbabej** [comment]
No worries, happy to help :slightly_smiling_face:
