### ISSUE TITLE
Support `rc` overwrites in report definition

### ISSUE THREAD

**Issue by mrossinek** [GothenburgBitFactory/taskwarrior#2579]
Similarly to how #2543 is adding support for overwriting configuration variables per context, this would be useful for custom report definitions.
The most simple example for this would be when working with a GTD workflow where you have implemented your inbox with a simple tag, e.g. `+in`.
Consider you are now at home (`context.home=+@home`) or at work (`context.work=+@work`) but want to view your inbox using a report like the following:
```
report.in.columns     = id,project,description
report.in.description = Inbox
report.in.filter      = limit:page (+in) (-COMPLETED) (-DELETED)
report.in.labels      = ID,Project,Description
```
You know always need to type `task rc.context:none in`.

Being able to overwrite this configuration option as part of the report definition could resolve that.

**Comment by tbabej** [comment]
Related to #2560 which is an explicit ask for a confiuration option for whether a particular report command uses context.

**Comment by tbabej** [comment]
I gave this a bit more thought and I think this would be highly non-trivial and perhaps a bit an overkill. The reason here is that command determination happens at much later stage than actual configuration parsing (and application of configuration overrides). You can even define an entire new command through configuration overrides (by defining a new custom report).

Given the primary use case that this was motivated by is now explicitly supported, I am leaning towards closing this request for now. We can always re-open if more arguments in favor of this feature arise - future visitors of this thread, please add comments here if you have some :slightly_smiling_face:

**Comment by mrossinek** [comment]
Sounds good to me! Is there already an ETA for the next release which will include this feature? I.e. is there a 2.7 planned or will I have to wait for 3.0?

**Comment by tbabej** [comment]
This is already on the development branch and will be part of 2.6, that is, released in couple of weeks.
