### ISSUE TITLE
Taskwarrior fails on importing a million tasks

### ISSUE THREAD

**Issue by bradyt** [GothenburgBitFactory/taskwarrior#2677]
CLI task version 2.6.1.

I've written a script that creates one million tasks, and tried to import that to Taskwarrior. The process is killed for reasons I don't know.

Interestingly, I can get them imported if I change m to 5, and n to 10. That's 100,000 tasks, imported 10 times. And Taskserver even accepts an upload of 1,000,000 updates, after setting `taskd config request.limit 0`.

I don't think this is really a bug necessarily, just an interesting measurement that some may find useful to understand the tool.

```sh
# This script resets `foo.json` to a single task, then increases the
# copies of that task ten fold, and does that m=6 times, for a total
# of 1,000,000 copies. It then imports those tasks n=1 times into CLI
# task.

touch foo.json
echo '{"description":"foo"}' > foo.json

m=6
n=1

for _ in $(seq 1 $m); do
    touch foo.json.tmp
    for _ in $(seq 1 10); do
        cat foo.json >> foo.json.tmp
    done
    mv foo.json.tmp foo.json
done

rm -r .task/*.data

for _ in $(seq 1 $n); do
    HOME=. task import foo.json
done
```

```
> sh script.sh
 add  51f14308-e834-497c-af73-d42b5f05afaa foo
 add  32d85a53-79ed-4c37-a715-6099b0c53733 foo
 ...
 add  52a69da8-6202-42c6-b80b-86f92527d13e foo
 add  ffba36fa-ce49-4759-bb57-3e8c127fa41e foo
Killed
```

**Comment by tbabej** [comment]
Could it be that the process simply ran out of memory?

**Comment by bradyt** [comment]
Oh, that's very likely. I was doing all tests in Docker. When I tried on host computer, it actually succeeds after half a minute, and monitoring the RAM suggests it climbs up to almost 3 GB of RAM before finishing.

**Comment by bradyt** [comment]
Oops, didn't mean to close.

But I don't know if this is really an issue to leave open. I'll leave it to you and team to decide.

**Comment by Oppen** [comment]
> Could it be that the process simply ran out of memory?

It may be a good idea to stream the import then, right? Or, since it's receiving a file, just `mmap` it.

**Comment by djmitche** [comment]
I don't think `task import` is meant to scale like this. In general, Taskwarrior often loads the task DB - at least pending tasks - into memory, so a million tasks is asking a lot.

**Comment by Oppen** [comment]
> I don't think `task import` is meant to scale like this. In general, Taskwarrior often loads the task DB - at least pending tasks - into memory, so a million tasks is asking a lot.

1M tasks does sound like a lot, but consider you may be tracking many state changes over the years of tasks and be migrating across versions and machines. The tasks may also contain arbitrary metadata. I used to take detailed notes of ideas that I would push as metadata to keep track of them.
Don't focus too much on the artificial example, but on whether or not doing things differently allows wider (legitimate) usage. I still think if the only issue is that it loads everything to memory always then the solution is to just not do that. I'd also rather bound the memory usage of my terminal programs unless there's a real reason that it can't be done.
All that said, do note the issue predates the SQLite version, so who knows if this issue is still valid.

**Comment by djmitche** [comment]
There are always trade-offs, and building TaskWarrior to scale to millions of tasks would preclude other, more desirable functionality, or at least make it more difficult to implement. Switching to a streaming model would make most reports (especially complex reports like burndown) much more difficult to implement, for example. TaskWarrior is fundamentally a getting-things-done tool, which means that it operates on a "human" scale. Humans don't track millions of tasks :)

So while this isn't technically impossible, I don't think it would be a good decision from an engineering perspective. Use-cases requiring millions of tasks might be better suited by bug-tracking tools or SaaS products like Asana.

**Comment by Oppen** [comment]
> There are always trade-offs, and building TaskWarrior to scale to millions of tasks would preclude other, more desirable functionality, or at least make it more difficult to implement.

Such as?

> Switching to a streaming model would make most reports (especially complex reports like burndown) much more difficult to implement, for example.

For import? It sounds like the import should behave just the same as creating the tasks one at a time, just faster. It's also the recommended migration path.

> TaskWarrior is fundamentally a getting-things-done tool, which means that it operates on a "human" scale. Humans don't track millions of tasks :)

Millions may be too much, but it depends on how much content each task has, how long you've been using TaskWarrior (I'd rather use it for years if I can), how granular they are, etc. Tens of thousands sound reasonable to me.

> So while this isn't technically impossible, I don't think it would be a good decision from an engineering perspective. Use-cases requiring millions of tasks might be better suited by bug-tracking tools or SaaS products like Asana.

One of the uses some people has is mirroring a bug tracker (I know not because I do it, but by the fact you can find hooks for that searching in the website).

I agree that *millions* is probably too much. But loading everything to memory still seems wasteful, and is known to crash the old server on sync for real users. That's an engineering flaw. That, again, may not apply to the new versions, I haven't checked.

**Comment by ryneeverett** [comment]
>  But loading everything to memory still seems wasteful...

I would tend to agree with this but this conversation has probably reached the point where we'd need to do cost-benefit analysis to make any progress -- At what volume of tasks does this actually present a problem? How would a streaming redesign be implemented and how would that impact maintainability?

> TaskWarrior is fundamentally a getting-things-done tool, which means that it operates on a "human" scale.

I found this statement striking in it's clarity, particularly after (agreeing with) [your comment regarding comparison with other tools](https://github.com/GothenburgBitFactory/taskwarrior/issues/3237#issuecomment-2134021872) and reflecting on how we might alternatively express taskwarrior's strengths better on the website (to facilitate people doing their own comparison). Interestingly, neither GTD nor "human scale" are mentioned prominently on the website or on the [philosophy page](https://taskwarrior.org/docs/philosophy/). Perhaps potential revision of the philosophy page and messaging around GTD would be a good community meeting agenda some time...
