### ISSUE TITLE
Wrong formatting on "task show" output.

### ISSUE THREAD

**Issue by saavedra29** [GothenburgBitFactory/taskwarrior#2710]
**DIAGNOSTICS**
```
task 2.6.1
   Platform: Linux

Compiler
    Version: 9.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.16.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.13
 Build type: release

Configuration
       File: /home/aris/.taskrc (found), 1454 bytes, mode 100664
       Data: /home/aris/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: 
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/aris/.task/hooks
             (-none-)

Tests
   Terminal: 170x52
       Dups: Scanned 1 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 1 tasks for broken references:
             No broken references found
```
When i run "task show" the output is not as in the 2.5.1 version but every 2 lines there is some whitish background. At the image below you can see the output of the command from the 2.6.1 version on the left and from the 2.5.1 version on the right. On both cases i use the exact same configuration/data.

![taskwarrior_bug](https://user-images.githubusercontent.com/8999952/147976151-fb054c18-6d85-40e1-95d4-8493485f862d.png)

**Comment by saavedra29** [comment]
Sorry i forgot to make clear that the 2.6.1 version was build from source while the 2.5.1 version was installed from the Linux Mint package manager which, as i see now, makes huge difference on file structure.

**Comment by serg3k** [comment]
@saavedra29 I guess this is expected behaviour - ncurses-based `Table` view for "show" command output was introduced with [v2.5.2](https://github.com/GothenburgBitFactory/taskwarrior/commit/90424774152ee2dfe0aba55ebd1d96b4f083ab4e#diff-ce964b138f8184d740f4ed67c4cd300bd5aa6e91f7933db9c8964596bde0c9a8), instead of `ViewText` view.

Color can be changed by setting color.alternate config entry:
```
task config color.alternate on
```

But width - from the first glance it looks like width of this output table can be changed by setting `defaultwidth` config parameter, but in practice this works only on wide terminals because minimal table width [is being forced](https://github.com/GothenburgBitFactory/libshared/blob/8baf2dbcad9ea24bb9f00a20d912df5da9b45113/src/Table.cpp#L96) by some particularly long rows, like this one:
![Screenshot 2022-01-04 at 22 04 42](https://user-images.githubusercontent.com/803865/148123914-80888783-ebbc-496f-bd27-4ab9743bf292.png)

Perhaps `Table` rendering could be adjusted in a way that shorter lines are not populated with `spaces` for table alignment so that there are less empty lines when resizing terminal.

**Comment by saavedra29** [comment]
@sergi-ko running `task config color.alternate on` corrected the background color but also the big width of every second line! I don't have any knowledge about ncurses though. Thank you very much for the help :)
