### ISSUE TITLE
How to disable news and highlight message?

### ISSUE THREAD

**Issue by gelerum** [GothenburgBitFactory/taskwarrior#3196]
Sometimes i get message about new version to see highlights. I don't want to change my config each time. I tried to set 9.9.0 version, but it didn't work. How can i disable it? If i can't disable it, we need this option.

**Comment by felixschurk** [comment]
I have in my `.taskrc` the setting `news.version=2.6.0` and then I do not get any news suddenly. 

Do you perhaps use the `news` command which displays the news?
 ```sh
 $ task news

==========================================
Taskwarrior 2.6.0 Major Release highlights
==========================================
......
```

**Comment by djmitche** [comment]
I saw this and eventually tracked it down to some config management of my home directory. It was rewriting the config file back to the "original" form, which didn't have the `news.version` string in it. It's a bit of an odd choice to put dynamic information like this in the config, but that's where it is :)

I suspect you could use something like `news.version=99.0.0` to disable it more-or-less forever.

**Comment by hakan-demirli** [comment]
> I suspect you could use something like `news.version=99.0.0` to disable it more-or-less forever.

If the news version is higher than currently installed version the message remains. 
However, as mentioned `news.version=2.6.0` does disable the message.
I am on 2.6.2. NixOS.

**Comment by terminatorbs** [comment]
is this really the only way to disable this? i just spent half an hour trying to get this message to shut up with no success, couldn't find anything in the config and chatGPT hallucinated 3 different config options that all didn't work, and i can't believe setting it to an arbitrarily high version is how it's done.

**Comment by terminatorbs** [comment]
is there really no way of actually permanently disabling this message? comments here are conflicting and i just... don't want to be bothered by this? am i crazy?

**Comment by djmitche** [comment]
I am amused at the multiple stories of ChatGPT hallucinating about Taskwarrior (in an earlier version of @terminatorbs's comment). It's a fun fad, hopefully gone soon!

I have my personal opinions about this but they don't represent the project. Maybe the best person to speak to this is @tbabej?

**Comment by tbabej** [comment]
The feature is designed to only show the news once per release, I think it is more annoying right now on the latest release because of the unresolved issue https://github.com/GothenburgBitFactory/taskwarrior/issues/3391 , which is the cause of repeated reminders to view news.

If there is interest in opting out of seeing news permanently (even if it's just once per release), we can introduce a new verbosity option. Verbosity flags are the canonical way of tweaking how much output `task` produces, so we could introduce `news` verbosity flag that users could disable in their config files, if they wish to do so. I would happily merge PR for that, though I would even more happily see #3391 fixed :slightly_smiling_face:

**Comment by terminatorbs** [comment]
maybe to add some more detail - the reason i tried to find a way to disable it (and admittedly got somewhat annoyed) is because the message popped up on a fresh install of taskwarrior, a time where it seemed especially useless to me.

also, i use at least 3 devices regularly, and was worried i'd have to remove each update notification several times, although that might be solved by syncing the taskrc. most of my config files don't need syncing too often though.

anyway, i'd be happy with a verbosity option.

**Comment by djmitche** [comment]
Those are both good points! I think we could make the default install set the current version.

**Comment by djmitche** [comment]
OK, I've filed three new issues related to this one -- thanks!

* #3497 - verbosity
* #3498 - fresh install
* #3499 - no news should be better news

**Comment by Necior** [comment]
#3497 got fixed today -- we've added an option to disable the "see 'task news' reminder".

There is no release with this change yet but it should be available in the next one. Stay tuned!
