### ISSUE TITLE
-DENABLE_SYNC=OFF is no longer supported

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3296]
From @jschleus in #3295:
> Additionally the cmake option -DENABLE_SYNC=OFF is no longer supported

**Comment by djmitche** [comment]
@jschleus, where did you see a reference to ENABLE_SYNC=OFF? I only see that in the ChangeLog from when sync support was added.

Or is the concern simply that the removal of this option was not mentioned in the release notes?

**Comment by jschleus** [comment]
> Or is the concern simply that the removal of this option was not mentioned in the release notes?

Exactly.

I found in old shell history files that I have originally used that cmake option. And since I don't need/want synchronisation I tried the option again.

Also to avoid the at least for me annoying output lines
 `There are X local changes.  Sync required.` 
(but until I find a sensible solution, this small problem I have solved simply by ignoring the error channel by adding `2>/dev/null`).
