### ISSUE TITLE
`task add` reports "Created task 0" after upgrade to 3.0.0

### ISSUE THREAD

**Issue by guludo** [GothenburgBitFactory/taskwarrior#3312]
#### To report a bug...

After upgrading to taskwarrior 3.0.0, the command `task add` reports id "0" for the created.

Here is an example:

```
$ task add Hello
Created task 0.
```

Output of `task diag` with redacted paths:

```

task 3.0.0
   Platform: Linux

Compiler
    Version: 13.2.1 20230801
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
     Commit: 3e41fb604
      CMake: 3.29.0
    libuuid: libuuid + uuid_unparse_lower
 Build type: 

Configuration
       File: <some-path> (found), 1869 bytes, mode 100644
       Data: <some-path> (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: nvim
Hooks
     System: Enabled
   Location: <some-path>
     Active: <some-path>    (executable) (symlink)
             <some-path>     (executable)
             <some-path> (executable)
   Inactive: 

Tests
   Terminal: 120x30
       Dups: Scanned 152 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 152 tasks for broken references:
             No broken references found

```

**Comment by djmitche** [comment]
From the diagnostics, I think this occurred after you imported your new tasks -- is that right? I tried importing my taskdb and then running `task add hello` and it produced the correct ID.

The code that gets this ID is https://github.com/GothenburgBitFactory/taskwarrior/blob/dfaf3dfcb2901785c91ddf9071f24f4805c15783/src/TDB2.cpp#L105-L115 so it's getting the "working set" (which is what maps tasks to their IDs) and looking up the task, then setting `task.id` if it finds one.

By any chance is the some configuration, perhaps a context, that is configuring new tasks to not be pending, and thus not in the working set?

Do other tasks appear correctly? If you run the same `task add hello` after listing tasks, does it assign a correct ID? Listing tasks should trigger a gc run, which should update the working set. But even if the working set was empty, I'd expect a new pending task to be assigned ID 1, and not 0.

**Comment by felixschurk** [comment]
I checked with the debugger, and it seems to me that the https://github.com/tbabej/taskpirate/blob/fc92860340defb4ff1f931070f6c979c30fb781c/on-add-pirate script/hook is messing with the task number. 

Up to https://github.com/GothenburgBitFactory/taskwarrior/blob/8a0a98d3efd58dc3354bc0b26a1bfc2b9ba9a843/src/TDB2.cpp#L126 the ID is set correctly however after this call the ID is somehow reset to zero. 
When I disabled the hook (make it inactive) the task is added and the output shows the right ID.

https://github.com/GothenburgBitFactory/taskwarrior/blob/8a0a98d3efd58dc3354bc0b26a1bfc2b9ba9a843/src/Hooks.cpp#L293
I think this line is where it does get messed up, as this one does reset the ID to 0.


A fix for this would be to change the order of the lines https://github.com/GothenburgBitFactory/taskwarrior/blob/8a0a98d3efd58dc3354bc0b26a1bfc2b9ba9a843/src/TDB2.cpp#L121-L126 e.g. moving the `Context::getContext()....` line 126 before we assign the right ID.

@djmitche Would this result in any side effects? Otherwise, I can prepare a PR for this.

Test are running without any additional failures:
```sh
❯ ./run_all
Passed:                          2700
Failed:                             0
Unexpected successes:               0
Skipped:                            0
Expected failures:                  4
Runtime:                         1.46 seconds
For details run 'make problems'
❯ ./problems
Failed:                        

Unexpected successes:          

Skipped:                       

Expected failures:             
lexer.t                             4
```
