### ISSUE TITLE
sync protocol errors should give better messages

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3332]
When sync to `taskwarrior-sync-server` fails, we get pretty terse messages, if anything.

Those should at least include the information from the HTTP response signalling the error.

**Comment by ryneeverett** [comment]
Was this resolved by #3362?

**Comment by djmitche** [comment]
Not entirely, no -- what messages there are will now be displayed, but the messages do not include the HTTP response.

**Comment by brewb4rt** [comment]
This would have been extremely helpful.  I've spent half a day trying to get sync with taskchampion-sync-server to work just to give up due to cryptic error messages ("failed to synchronize to server" would be nice to know why - do you see the server? Can you access it? Is there a version mismatch?) :/ will try again in a few weeks or months and live with a local only task list until then

**Comment by djmitche** [comment]
With the latest `develop`, I get the following from `task sync` in various conditions:
```
Failed to synchronize with server: http://localhost/v1/client/get-child-version/00000000-0000-0000-0000-000000000000: Connection Failed: Connect error: Connection refused (os error 111): Connection refused (os error 111)
```
```
Failed to synchronize with server: Response does not have X-Parent-Version-Id header
```
```
Failed to synchronize with server: http://localhost:8000/v1/client/get-child-version/00000000-0000-0000-0000-000000000000: status code 501
```
so I think this is working well enough. https://github.com/GothenburgBitFactory/taskchampion/pull/402 gets that last bit -- the status text.
