### ISSUE TITLE
Test scripts assume `task` is at `src/task`.

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3351]
Instead, `task` appears in the build directory. Ideally we could figure out from cmake where that is?

**Comment by felixschurk** [comment]
This is when running the `./run_all` script in the `./test` folder right?

Does it deliver the desired results if you run the `./build/test/run_all` script in the build folder? Then it should work?

# Steps to reproduce
```sh
cmake -S . -B build
cmake --build build --target test --parallel 4
```

## Output when in build directory
```sh
cd build/test

/workspaces/taskwarrior/build/test (develop) $ ./run_all 
Passed:                          2700
Failed:                             0
Unexpected successes:               0
Skipped:                            0
Expected failures:                  4
Runtime:                         1.21 seconds
For details run 'make problems'
```

## Output when in source test directory
```sh
cd test

/workspaces/taskwarrior/test (develop) $ ./run_all 
Passed:                           117
Failed:                           691
Unexpected successes:               0
Skipped:                           17
Expected failures:                  4
Runtime:                         8.31 seconds
For details run 'make problems'
```


If that is the behaviour you where describing one should probably update the pull request template, to make it clear that the test reside in `build`.

https://github.com/GothenburgBitFactory/taskwarrior/blob/7c465ceb8fd58e8eb7b9ff3aedd94deb691a9cf3/.github/pull_request_template.md?plain=1#L8

**Comment by felixschurk** [comment]
I just came across [configure_file](https://cmake.org/cmake/help/latest/command/configure_file.html) and I think we could use that in quite some places where we currently have hardcoded paths in the performance or test scripts to the task executable or other sources. 

So the idea would be to copy the corresponding files over to the build directory and replace the path then accordingly (automatically done by CMake). 
This way it would also easily allow testing different builds or also hopefully more easily enable coverage test etc on the test suite, also different compilers etc as then the build directory can be named arbitrary e.g. `build-gcc` and `build-clang` could both exist and run the test suite.

**Comment by djmitche** [comment]
I was running a single test script (`./test/import.t`), but what you've shown is also a bug -- that 2700 number is only representing the C++ tests, not the Python tests (which is why it runs so fast, I think).

I think your suggestion of copying the files to ./build and updating them to contain the right path (only `test/basetest/utils.py` needs the path) is a good one.

**Comment by felixschurk** [comment]
## Some thoughts about testing/performance etc..
As a general regard for the tests and how we call it.
I thought a bit about it and for me personally it is quite confusing how one does run all test (unit tests, integration tests etc.) as well as how one could build only a specific test.
E.g. when I would like to work on a feature which affects only a subset of tests it would be beneficial to only run the corresponding tests when developing, and then have a simple interface to run all test when one would be ready.
Also on this approach I think most of the IDEs should be able to recognize the proper tests and then also coverage etc should be quite simple to add in the future.

## What could one do?
I guess the most forward way would be to use [CTest](https://cmake.org/cmake/help/latest/manual/ctest.1.html) as it is bundled with CMake and thus already part of our toolchain. 
With CTest one can also execute shell scripts, python files etc. meaning we do not need to rework existing tests, only how they are executed/build with CMake.

## How would it look like? Some demo repository
I just searched and found [ctest-demo](https://github.com/tgamblin/ctest-demo/) as a simple sample repository (not affiliated with me or something). Maybe to have a feeling do:
```sh
git clone https://github.com/tgamblin/ctest-demo.git
cd ctest-demo
cmake -S . -B build
cmake --build build
ctest --test-dir build
```
This would give a first overview how it is looking/how it might be looking.
If one would like to see a bit bigger example [this repository](https://github.com/STCE-at-RWTH/AD-Driver-Generator/tree/develop) I worked on and we used there the CTest for the test invokation (Mainly liked because its a bit larger than the sample, but yet I am able to understand everything :D).

I played around already a bit with the taskwarrior repository, and I should be able to implement it here.

## What would need to be done?
* [ ] adding all existing tests to the CMakeLists
* [ ] update documentation for the developer
* [ ] update build pipelines to pickup new schema

@djmitche and @ryneeverett if you guys think it's a reasonable idea to go this direction I would start working on it, probably with a separate issue.

**Comment by ryneeverett** [comment]
@felixschurk I have no opinion on the proposal but it seems like this could just be a documentation issue. [The docs](https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/doc/devel/contrib/development.md#run-the-test-suite) don't mention that the tests are built on bats/tap, which I suspect offers a comparable set of features, though those features are undocumented and may not actually be exposed the way we're invoking them.

**Comment by djmitche** [comment]
I agree that working with tests right now is pretty awkward - for C++ tests you need to build the test and then run it in separate invocations. For Python tests, you can just run the script. But, that does have the problem I encountered in the beginning of this issue.

It looks like CTest doesn't have TAP support - it just looks at each target as a test case. TAP is nice in that it can allow a test harness to get pretty granular counts for tests that passed / failed (or unexpectedly did the wrong one). But, I'm not sure that's actually helpful for Taskwarrior. For one thing, running the entire suite currently produces thousands of lines of output, and then at the end says "one test failed" and it can be tricky to figure out which one. I think I'd rather know that target `test/foo.t` failed, and maybe see the entire output from that target, or just re-run that single target.

It does seem like CTest would do a good job of this. It also seems like this would be a pretty quick CL to put together, although pretty repetitive. Maybe this is a good case for ["exploring through code"](https://mastodon.social/@djmitche/112289805088983197)?
