### ISSUE TITLE
Value limit=page not recognized.

### ISSUE THREAD

**Issue by Andonome** [GothenburgBitFactory/taskwarrior#3465]
When I run `task show`, I get the following message:

```
Your .taskrc file contains these unrecognized variables:
  limit

```
Checking the taskrc file, I have `limit=page`.

If I run `task list` without this, I get more tasks than can fit onto the terminal (`urxvtc`).
But when running with `limit=page`, I only get the top tasks, which can fit into the current terminal.

So `limit=page` has been recognized, and it's working as intended.  But then again, the vim highlights won't show this as a proper option, so maybe it's been forgotten about?

**Comment by djmitche** [comment]
The `show` command's implementation has a long list of recognize config options. Maybe this was just omitted from the list? If so, a PR to restore it would be great (and a check that it appears in the manpage as well).

**Comment by Andonome** [comment]
I've put in a [pull request](https://github.com/GothenburgBitFactory/taskwarrior/pull/3466).

**Comment by djmitche** [comment]
Still need to add the config to `.taskrc` :)

**Comment by Andonome** [comment]
The [PR](https://github.com/GothenburgBitFactory/taskwarrior/pull/3467) is in now ;)

**Comment by djmitche** [comment]
Thanks for the fixes!

We'd love to have further help. Is there a particular thing you have in mind to improve? From your other repositories it seems you do a lot of technical (in the sense of very-detailed!) writing. I think the docs on https://taskwarrior.org/docs/ could use some updating. They certainly feel like they are the collected notes of a decade of developers, rather than a conscientious attempt to document an application. If you'd like to get more involved with coding, we can find something in that direction, too.

**Comment by Andonome** [comment]
It's in the task list.

The task files are a little difficult to read. Would people appreciate having them in markdown format, then automatically translated with `lowdown`?  The [lowdown](https://kristaps.bsd.lv/lowdown) program allows easy translation to html, pdf, and various man page formats.

**Comment by djmitche** [comment]
That sounds good -- I only _barely_ understand troff!
