### ISSUE TITLE
All Python tests fail?

### ISSUE THREAD

**Issue by doronbehar** [GothenburgBitFactory/taskwarrior#3707]
On NixOS, we experience these errors when trying to run tests:

https://gist.github.com/doronbehar/6a76e09d64a2f515548a53afd72d9663

Any idea why is that?

**Comment by djmitche** [comment]
Just to check the obvious, you are building the target `test_runner`, right? I get the same error if I delete $BUILD/test/test_executable. Similarly with the .py files - those are generated (copied) in the configure stage, so if they are missing then something didn't run.

**Comment by doronbehar** [comment]
OK running `make test_runner` before running `make check` helped for the cpp tests, but not for the Python tests (a full build log this time):

https://gist.github.com/doronbehar/6063de9bbeac7ac31ad9dd124c9ba9ab

The question now is, what is the make target that would copy the Python files to the correct place? And why do I have to run `make test_runner` by myself?

**Comment by djmitche** [comment]
Hm, I use the Ninja backend, and there is no `check` target there:
```
⸩ cmake --build build -t check
ninja: error: unknown target 'check', did you mean 'calc'?
```
Even so, the [build instructions](https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/doc/devel/contrib/development.md#run-the-test-suite) do specify building `test_runner` first. I think that's because the `ctest` binary can't build targets. But as I said earlier, my understanding of CMake is minimal.

For me, just running the configure stage is enough to put the .py files into the build directory:
```
⸩ rm -rf build
⸩ cmake -DCMAKE_BUILD_TYPE=Debug -S. -Bbuild .
...
⸩ find build/test -name '*.py' | wc -l
131
```

That the `.sh` tests succeed, while the `.py` do not, suggests that the test files _exist_ but their shebang line (`#!/usr/bin/env python3`) is pointing to something which does not exist.

**Comment by doronbehar** [comment]
Thanks for the link. I too observe the Python files there, and `python3` is supposed to be available during that phase. I suspect the issues I'm experiencing now are still related to the `cxxbridge` related issues. So I'm hoping for a version compatible and comfortable resolution for us in that regard, and then I'll insist further with the Python tests...

**Comment by doronbehar** [comment]
OK I managed to fix that. I had to use a Nix tool called `patchShebangs` for all the. I still encountered individual failures, and these I'll report in a different issue.
