### ISSUE TITLE
[TW-352] Undo command is not removing backlog.data entries

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#387]
_Paul Beckingham on 2013-05-27T16:32:37Z says:_ 

 When an undo completes, it removes a transaction from undo.data, but leaves the corresponding transaction in backlog.data.  Not good.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-05-27T16:32:37Z
Modified: 2014-02-09T01:36:03Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-07-06T14:42:19Z says:_ 

 I'm no longer sure it even needs to.  Thinking...

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-10-06T18:01:03Z says:_ 

 Works, and disables undo for cases where sync has occurred.  Undo always was a local feature, now with sync it becomes less useful.

**Comment by Rahlir** [comment]
The fact that undo does not remove entry in `backlog.data` means that undo modifications get synced with `task sync`. This is quite annoying as it means you get a lot of modifications in journal history after undos and `task sync`. This should be fixed. (Of course I am guessing since work is underway on a complete rewrite with different sync model, this might not be a priority for the 2.* version)

**Comment by djmitche** [comment]
The new interaction is that things can be undone before they are sync'd, which has the result of pretending they never occurred. Once they are sync'd, though, that's a much more ambiguous proposition so undo is not supported.

**Comment by Rahlir** [comment]
You mean this is the change in the new rewrite correct?

I understand that undo after sync is complicated (and was not advocating for implementing that). My point was that in the current stable version of taskwarrior, the undo does not work properly even _before_ sync: since `backlog.data` is not modified with undo, even though the modification is reverted the information about the two modifications get pushed to task server with sync command.

**Comment by djmitche** [comment]
I agree that's a bug! If there are plans to release another 2.x (which there are not at the moment), we should address it.
